{{PREFIXES}}

SELECT DISTINCT ?section ?chunk ?text ?index WHERE {
    ?tag rdf:type ki4kmu:Tag ;
         rdfs:label ?tagLabel .
    FILTER(CONTAINS(LCASE(STR(?tagLabel)), LCASE({{keyword_sparql}})))
    
    ?section ki4kmu:hasTag ?tag ;
             rdf:type ki4kmu:Section .
    
    ?section ki4kmu:isContained ?chunk .
    ?chunk rdf:type ki4kmu:Chunk ;
           ki4kmu:text ?text ;
           ki4kmu:chunk_index ?index .
}
ORDER BY ?index
