{{PREFIXES}}

SELECT DISTINCT ?section ?chunk ?text ?index WHERE {
    ?concept rdf:type ki4kmu:Concept ;
         rdfs:label ?conceptLabel .
    FILTER(CONTAINS(LCASE(STR(?conceptLabel)), LCASE({{keyword_sparql}})))

    ?section ki4kmu:hasConcept ?concept ;
             rdf:type ki4kmu:Section .

    ?section ki4kmu:isContained ?chunk .
    ?chunk rdf:type ki4kmu:Chunk ;
           ki4kmu:text ?text ;
           ki4kmu:chunk_index ?index .
}
ORDER BY ?index
